# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Standard-library command framework shared by cuPhoton components."""

from .app import (
    CLI,
    CommandLine,
    ComponentCLI,
    build_component_cli,
    main,
    run_component,
)
from .command import (
    Command,
    CommandCollisionError,
    CommandError,
    CommandRegistrationError,
    InvariantAwareCommand,
    collect_invariants,
    command_name,
    command_shortname,
    configure_logging,
    discover_command_classes,
    normalize_log_level,
    resolve_log_level,
)
from .component import (
    COMPONENT_REGISTRY,
    COMPONENTS,
    ComponentSpec,
    get_component,
)
from .context import ApplicationContext
from .invariants import (
    BoolInvariant,
    CSVIntegerInvariant,
    CSVInvariant,
    CSVStringInvariant,
    DirectoryInvariant,
    ExistingPathInvariant,
    FloatInvariant,
    IntegerInvariant,
    Invariant,
    InvariantDefinitionError,
    InvariantError,
    MkDirectoryInvariant,
    MultipleSetInvariant,
    NonNegativeIntegerInvariant,
    OptionCollisionError,
    OutPathInvariant,
    PairInvariant,
    PathInvariant,
    PathValueInvariant,
    PositionalDefinitionError,
    PositionalInvariant,
    PositiveIntegerInvariant,
    SequenceInvariant,
    SetInvariant,
    StringInvariant,
    VariablePositionalInvariant,
)

__all__ = [
    "COMPONENT_REGISTRY",
    "COMPONENTS",
    "ApplicationContext",
    "CLI",
    "BoolInvariant",
    "CSVIntegerInvariant",
    "CSVInvariant",
    "CSVStringInvariant",
    "Command",
    "CommandCollisionError",
    "CommandError",
    "CommandLine",
    "CommandRegistrationError",
    "ComponentCLI",
    "ComponentSpec",
    "DirectoryInvariant",
    "ExistingPathInvariant",
    "FloatInvariant",
    "IntegerInvariant",
    "Invariant",
    "InvariantAwareCommand",
    "InvariantDefinitionError",
    "InvariantError",
    "MkDirectoryInvariant",
    "MultipleSetInvariant",
    "NonNegativeIntegerInvariant",
    "OutPathInvariant",
    "OptionCollisionError",
    "PairInvariant",
    "PathInvariant",
    "PathValueInvariant",
    "PositiveIntegerInvariant",
    "PositionalInvariant",
    "PositionalDefinitionError",
    "SequenceInvariant",
    "SetInvariant",
    "StringInvariant",
    "VariablePositionalInvariant",
    "build_component_cli",
    "collect_invariants",
    "command_name",
    "command_shortname",
    "configure_logging",
    "discover_command_classes",
    "get_component",
    "main",
    "normalize_log_level",
    "resolve_log_level",
    "run_component",
]
